# -*- coding: utf-8 -*-
"""Prompt_Market1501

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mqZGPc3pjXM-NsJD8m6Wnr7I0ipEj3fi
"""

# ╔══════════════════════════════════════════════════════════════╗
# ║  CELL 1: MOUNT GOOGLE DRIVE                                  ║
# ╚══════════════════════════════════════════════════════════════╝

from google.colab import drive
drive.mount('/content/drive')

import os
CHECKPOINT_DIR = '/content/drive/MyDrive/PromptPAR_checkpoints/Vit_Market1501'
os.makedirs(CHECKPOINT_DIR, exist_ok=True)
os.makedirs('/data/jinjiandong', exist_ok=True)

print(f"✅ Checkpoint dir: {CHECKPOINT_DIR}")

# Commented out IPython magic to ensure Python compatibility.
# ╔══════════════════════════════════════════════════════════════╗
# ║  CELL 3: CLONE REPOSITORIES                                  ║
# ╚══════════════════════════════════════════════════════════════╝

import os
import shutil

# %cd /content

# Clone OpenPAR
if os.path.exists('/content/OpenPAR'):
    shutil.rmtree('/content/OpenPAR')
! git clone https://github.com/Event-AHU/OpenPAR.git
print("✅ Cloned OpenPAR")

# Clone Market-1501 Attributes
if os.path.exists('/content/Market-1501_Attribute'):
    shutil.rmtree('/content/Market-1501_Attribute')
!git clone https://github.com/vana77/Market-1501_Attribute.git
print("✅ Cloned Market-1501_Attribute")

# Verify
!ls -la /content/

# Commented out IPython magic to ensure Python compatibility.
# ╔══════════════════════════════════════════════════════════════╗
# ║  CELL 4: CÀI ĐẶT DEPENDENCIES                                ║
# ╚══════════════════════════════════════════════════════════════╝

# %cd /content/OpenPAR/PromptPAR

! pip install -q ftfy regex tqdm easydict scipy
!pip install -q git+https://github.com/openai/CLIP.git

print("\n✅ Dependencies installed")

# Commented out IPython magic to ensure Python compatibility.
# ╔══════════════════════════════════════════════════════════════╗
# ║  CELL 5: TẢI MARKET-1501 DATASET                             ║
# ╚══════════════════════════════════════════════════════════════╝

import os

os.makedirs('/content/data', exist_ok=True)
# %cd /content/data

# Tải Market-1501
if not os.path. exists('/content/data/Market-1501-v15.09.15'):
    print("🔄 Đang tải Market-1501...")
    !pip install -q gdown
    !gdown "https://drive.google.com/uc?id=0B8-rUzbwVRk0c054eEozWG9COHM" -O Market-1501-v15.09.15.zip --fuzzy
    !unzip -q Market-1501-v15.09.15.zip
    !rm Market-1501-v15.09.15. zip
    print("✅ Đã tải và giải nén Market-1501")
else:
    print("✅ Market-1501 đã tồn tại")

! ls -la /content/data/Market-1501-v15.09.15/

# ╔══════════════════════════════════════════════════════════════╗
# ║  CELL 6: TẢI VIT PRETRAINED MODEL                            ║
# ╚══════════════════════════════════════════════════════════════╝

import os

os.makedirs('/data/jinjiandong', exist_ok=True)

vit_path = '/data/jinjiandong/jx_vit_base_p16_224-80ecf9dd.pth'

if not os.path.exists(vit_path):
    print("🔄 Đang tải ViT pretrained...")
    !wget -q https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-vitjx/jx_vit_base_p16_224-80ecf9dd.pth -O {vit_path}

if os.path.exists(vit_path):
    size = os.path.getsize(vit_path) / 1024 / 1024
    print(f"✅ ViT pretrained: {size:.1f} MB")
else:
    print("❌ Tải ViT thất bại!")

# Commented out IPython magic to ensure Python compatibility.
# ╔══════════════════════════════════════════════════════════════╗
# ║  CELL 7: SỬA CODE PROMPTPAR ĐỂ HỖ TRỢ MARKET1501             ║
# ╚══════════════════════════════════════════════════════════════╝

import os
import shutil

# Clone lại để đảm bảo code sạch
# %cd /content
if os.path.exists('/content/OpenPAR'):
    shutil.rmtree('/content/OpenPAR')
! git clone -q https://github.com/Event-AHU/OpenPAR.git
print("✅ Cloned fresh OpenPAR")

# ========== 1. SỬA clip/model.py ==========
model_py = '/content/OpenPAR/PromptPAR/clip/model.py'

with open(model_py, 'r') as f:
    lines = f.readlines()

new_lines = []
for line in lines:
    # Sửa dòng assert
    if "assert args.dataset in [" in line and "Market1501" not in line:
        new_lines.append("assert args.dataset in ['PA100k', 'RAPV1','RAPV2','PETA','WIDER','PETAzs','RAPzs','UPAR','YCJC','RAPV1Expand','Market1501'], \\\n")
    # Sửa dòng datasets_attrnum
    elif "datasets_attrnum=" in line and "Market1501" not in line:
        new_lines. append("datasets_attrnum={'PA100k':26,'RAPV1':51,'PETA':35,'PETAzs':35,'UPAR':40,'RAPzs':53,'RAPV2':54,'WIDER':14,'RAPV1Expand':51,'Market1501':27}\n")
    else:
        new_lines.append(line)

with open(model_py, 'w') as f:
    f. writelines(new_lines)

print("✅ Đã sửa clip/model.py")

# ========== 2. SỬA dataset/AttrDataset.py ==========
attr_py = '/content/OpenPAR/PromptPAR/dataset/AttrDataset.py'

with open(attr_py, 'r') as f:
    content = f.read()

# Thêm Market1501
content = content.replace(
    "['PA100k', 'RAPV1','RAPV2','PETA','WIDER','RAPzs','PETAzs','UPAR','YCJC',]",
    "['PA100k', 'RAPV1','RAPV2','PETA','WIDER','RAPzs','PETAzs','UPAR','YCJC','Market1501']"
)

# Sửa đường dẫn dataset
content = content. replace(
    "dataset_dir='/data/jinjiandong/datasets/'",
    "dataset_dir='/content/data/'"
)

with open(attr_py, 'w') as f:
    f.write(content)

print("✅ Đã sửa dataset/AttrDataset.py")

# ========== VERIFY ==========
print("\n📋 Verify model.py:")
with open(model_py, 'r') as f:
    for i, line in enumerate(f, 1):
        if 'datasets_attrnum' in line:
            print(f"   Line {i}: {line.strip()[:70]}...")
            if "'Market1501':27" in line:
                print("   ✅ Market1501 = 27 attributes")
            else:
                print("   ❌ Chưa đúng!")
            break

# ╔══════════════════════════════════════════════════════════════╗
# ║  CELL 7 FIX: SỬA TRỰC TIẾP FILE MODEL.PY                     ║
# ╚══════════════════════════════════════════════════════════════╝

model_py = '/content/OpenPAR/PromptPAR/clip/model.py'

with open(model_py, 'r') as f:
    content = f.read()

# Hiển thị trước khi sửa
print("🔍 TRƯỚC KHI SỬA:")
for line in content.split('\n')[13:19]:
    print(f"   {line[:80]}")

# Sửa tất cả các pattern có thể
replacements = [
    # Pattern 1
    ("datasets_attrnum={'PA100k':26,'RAPV1':51,'PETA':35,'PETAzs':35,'UPAR':40,'RAPzs':53,'RAPV2':54,'WIDER':14,\"RAPV1Expand\":51}",
     "datasets_attrnum={'PA100k':26,'RAPV1':51,'PETA':35,'PETAzs':35,'UPAR':40,'RAPzs':53,'RAPV2':54,'WIDER':14,'RAPV1Expand':51,'Market1501':27}"),
    # Pattern 2 (nếu đã có Market1501 nhưng sai số)
    ("'Market1501':39", "'Market1501':27"),
    # Assert pattern
    ("['PA100k', 'RAPV1','RAPV2','PETA','WIDER','PETAzs','RAPzs','UPAR','YCJC',\"RAPV1Expand\"]",
     "['PA100k', 'RAPV1','RAPV2','PETA','WIDER','PETAzs','RAPzs','UPAR','YCJC','RAPV1Expand','Market1501']"),
]

for old, new in replacements:
    if old in content:
        content = content. replace(old, new)
        print(f"\n✅ Đã thay thế pattern")

with open(model_py, 'w') as f:
    f.write(content)

# Hiển thị sau khi sửa
print("\n🔍 SAU KHI SỬA:")
with open(model_py, 'r') as f:
    content = f.read()
for line in content.split('\n')[13:19]:
    print(f"   {line[:80]}")

# Verify
if "'Market1501':27" in content:
    print("\n✅ OK!  Market1501 = 27")
else:
    print("\n❌ Chưa sửa được!  Cần sửa thủ công")

# ╔══════════════════════════════════════════════════════════════╗
# ║  CELL 8: TẠO DATASET PICKLE CHO MARKET1501                   ║
# ╚══════════════════════════════════════════════════════════════╝

import scipy.io
import numpy as np
import os
import pickle
import shutil
from easydict import EasyDict

# ========== PATHS ==========
MARKET_DIR = '/content/data/Market-1501-v15.09.15'
ATTR_FILE = '/content/Market-1501_Attribute/market_attribute.mat'
SAVE_DIR = '/content/data/Market1501'

# ========== CHECK FILES ==========
print("🔍 Kiểm tra files...")
if not os.path. exists(MARKET_DIR):
    raise Exception("❌ Chưa có Market-1501!  Chạy Cell 5 trước.")
if not os.path. exists(ATTR_FILE):
    raise Exception("❌ Chưa có market_attribute.mat! Chạy Cell 3 trước.")
print("✅ Files OK")

# ========== LOAD . MAT FILE ==========
mat_data = scipy. io.loadmat(ATTR_FILE)
market_attr = mat_data['market_attribute'][0][0]
train_attr_mat = market_attr['train'][0][0]
test_attr_mat = market_attr['test'][0][0]

# Lấy tên attributes TỪ FILE . MAT (27 attributes)
attr_names = [name for name in train_attr_mat.dtype. names if name != 'image_index']
print(f"📊 Attributes từ . mat: {len(attr_names)}")

# ========== GET IMAGE LISTS ==========
train_dir = os.path. join(MARKET_DIR, 'bounding_box_train')
test_dir = os.path. join(MARKET_DIR, 'bounding_box_test')

train_images = sorted([f for f in os. listdir(train_dir)
                      if f.endswith('.jpg') and not f.startswith('-1')])
test_images = sorted([f for f in os. listdir(test_dir)
                     if f.endswith('.jpg') and not f.startswith('-1') and not f.startswith('0000')])

print(f"🖼️ Train images: {len(train_images)}")
print(f"🖼️ Test images: {len(test_images)}")

# ========== CREATE DATASET ==========
image_name_list = []
label_list = []
train_idx = []
test_idx = []
idx = 0

# Process TRAINING images
print("\n🔄 Processing training images...")
for img_name in train_images:
    try:
        identity_id = int(img_name.split('_')[0])
        if 1 <= identity_id <= 751:
            image_name_list.append(os.path.join('bounding_box_train', img_name))
            attr_idx = identity_id - 1
            label = [int(train_attr_mat[attr_name][0][attr_idx]) - 1
                     if int(train_attr_mat[attr_name][0][attr_idx]) > 0 else 0
                     for attr_name in attr_names]
            label_list.append(label)
            train_idx.append(idx)
            idx += 1
    except:
        continue
print(f"   ✅ Train samples: {len(train_idx)}")

# Process TEST images
print("🔄 Processing test images...")
for img_name in test_images:
    try:
        identity_id = int(img_name.split('_')[0])
        if 1 <= identity_id <= 750:
            image_name_list.append(os.path. join('bounding_box_test', img_name))
            attr_idx = identity_id - 1
            label = [int(test_attr_mat[attr_name][0][attr_idx]) - 1
                     if int(test_attr_mat[attr_name][0][attr_idx]) > 0 else 0
                     for attr_name in attr_names]
            label_list. append(label)
            test_idx. append(idx)
            idx += 1
    except:
        continue
print(f"   ✅ Test samples: {len(test_idx)}")

# ========== CREATE EASYDICT ==========
dataset = EasyDict()
dataset.description = 'market1501'
dataset.root = SAVE_DIR
dataset. image_name = image_name_list
dataset.label = np.array(label_list, dtype=np.float32)
dataset. attributes = attr_names  # 27 attributes từ .mat

dataset.partition = EasyDict()
dataset.partition. train = np.array(train_idx, dtype=np.int64)
dataset.partition.val = np.array([], dtype=np.int64)
dataset. partition.test = np.array(test_idx, dtype=np.int64)
dataset.partition.trainval = np.array(train_idx, dtype=np.int64)

# Weights
train_labels = dataset.label[dataset. partition.train]
label_ratio = np.clip(np.mean(train_labels, axis=0), 0.01, 0.99)
dataset.weight_train = np.exp(-label_ratio). astype(np. float32)
dataset.weight_trainval = dataset.weight_train. copy()

# ========== SAVE ==========
if os. path.exists(SAVE_DIR):
    shutil.rmtree(SAVE_DIR)
os.makedirs(SAVE_DIR)

pkl_path = os.path. join(SAVE_DIR, 'pad. pkl')
with open(pkl_path, 'wb') as f:
    pickle.dump(dataset, f)
print(f"\n✅ Saved: {pkl_path}")

os.symlink(train_dir, os. path.join(SAVE_DIR, 'bounding_box_train'))
os.symlink(test_dir, os. path.join(SAVE_DIR, 'bounding_box_test'))
print("✅ Created symlinks")

# ========== VERIFY ==========
print("\n" + "=" * 60)
print("📋 DATASET SUMMARY")
print("=" * 60)
print(f"✅ Labels shape: {dataset. label.shape}")
print(f"✅ Attributes: {len(dataset. attributes)}")
print(f"✅ Train: {len(dataset.partition. train)}")
print(f"✅ Test: {len(dataset.partition. test)}")

# Verify file exists
if os.path.exists(pkl_path):
    size = os.path. getsize(pkl_path) / 1024 / 1024
    print(f"✅ pad.pkl: {size:.2f} MB")

if len(dataset.attributes) == dataset.label.shape[1]:
    print(f"\n🎉 OK!  attributes = labels = {len(dataset.attributes)}")
else:
    print(f"\n❌ MISMATCH!")

# ╔══════════════════════════════════════════════════════════════╗
# ║  TẠO PAD.PKL                                                 ║
# ╚══════════════════════════════════════════════════════════════╝

import scipy.io
import numpy as np
import os
import pickle
import shutil
from easydict import EasyDict

# ========== PATHS ==========
MARKET_DIR = '/content/data/Market-1501-v15.09.15'
ATTR_FILE = '/content/Market-1501_Attribute/market_attribute.mat'
SAVE_DIR = '/content/data/Market1501'

# Xóa và tạo lại thư mục
if os.path.exists(SAVE_DIR):
    shutil.rmtree(SAVE_DIR)
os.makedirs(SAVE_DIR)

# ========== LOAD . MAT FILE ==========
mat_data = scipy.io. loadmat(ATTR_FILE)
market_attr = mat_data['market_attribute'][0][0]
train_attr_mat = market_attr['train'][0][0]
test_attr_mat = market_attr['test'][0][0]

# Lấy 27 attributes từ . mat
attr_names = [name for name in train_attr_mat.dtype.names if name != 'image_index']
print(f"📊 Attributes: {len(attr_names)}")

# ========== GET IMAGE LISTS ==========
train_dir = os.path. join(MARKET_DIR, 'bounding_box_train')
test_dir = os.path. join(MARKET_DIR, 'bounding_box_test')

train_images = sorted([f for f in os.listdir(train_dir)
                      if f.endswith('.jpg') and not f.startswith('-1')])
test_images = sorted([f for f in os. listdir(test_dir)
                     if f.endswith('.jpg') and not f.startswith('-1') and not f.startswith('0000')])

print(f"🖼️ Train: {len(train_images)}, Test: {len(test_images)}")

# ========== CREATE DATASET ==========
image_name_list = []
label_list = []
train_idx = []
test_idx = []
idx = 0

# TRAINING
for img_name in train_images:
    try:
        identity_id = int(img_name.split('_')[0])
        if 1 <= identity_id <= 751:
            image_name_list.append(os.path.join('bounding_box_train', img_name))
            attr_idx = identity_id - 1
            label = [max(0, int(train_attr_mat[attr_name][0][attr_idx]) - 1) for attr_name in attr_names]
            label_list.append(label)
            train_idx.append(idx)
            idx += 1
    except:
        continue

# TEST
for img_name in test_images:
    try:
        identity_id = int(img_name.split('_')[0])
        if 1 <= identity_id <= 750:
            image_name_list.append(os.path. join('bounding_box_test', img_name))
            attr_idx = identity_id - 1
            label = [max(0, int(test_attr_mat[attr_name][0][attr_idx]) - 1) for attr_name in attr_names]
            label_list.append(label)
            test_idx.append(idx)
            idx += 1
    except:
        continue

print(f"✅ Train: {len(train_idx)}, Test: {len(test_idx)}")

# ========== CREATE EASYDICT ==========
dataset = EasyDict()
dataset.description = 'market1501'
dataset.root = SAVE_DIR
dataset. image_name = image_name_list
dataset.label = np.array(label_list, dtype=np.float32)
dataset. attributes = attr_names

dataset.partition = EasyDict()
dataset.partition.train = np.array(train_idx, dtype=np.int64)
dataset.partition.val = np.array([], dtype=np.int64)
dataset. partition.test = np.array(test_idx, dtype=np.int64)
dataset.partition.trainval = np.array(train_idx, dtype=np.int64)

# Weights
train_labels = dataset.label[dataset.partition.train]
label_ratio = np.clip(np.mean(train_labels, axis=0), 0.01, 0.99)
dataset.weight_train = np.exp(-label_ratio). astype(np.float32)
dataset.weight_trainval = dataset.weight_train. copy()

# ========== SAVE PICKLE ==========
pkl_path = os. path.join(SAVE_DIR, 'pad.pkl')
with open(pkl_path, 'wb') as f:
    pickle.dump(dataset, f)

# ========== CREATE SYMLINKS ==========
os.symlink(train_dir, os. path.join(SAVE_DIR, 'bounding_box_train'))
os.symlink(test_dir, os. path.join(SAVE_DIR, 'bounding_box_test'))

# ========== VERIFY ==========
print("\n" + "=" * 60)
if os.path.exists(pkl_path):
    size = os.path. getsize(pkl_path) / 1024 / 1024
    print(f"✅ CREATED: {pkl_path} ({size:.2f} MB)")
    print(f"✅ Labels: {dataset.label.shape}")
    print(f"✅ Attributes: {len(dataset.attributes)}")
    print(f"\n🎉 THÀNH CÔNG! Chạy Cell 10 để training")
else:
    print("❌ THẤT BẠI!")

# ╔══════════════════════════════════════════════════════════════╗
# ║  CELL 9: TRAINING CONFIGURATION                              ║
# ╚══════════════════════════════════════════════════════════════╝

# ==================== THAY ĐỔI Ở ĐÂY ====================
EPOCHS = 30              # Test: 3 | Chạy thật: 30
BATCH_SIZE = 16
SAVE_FREQ = 5           # Lưu checkpoint mỗi N epoch
# ========================================================

print("=" * 60)
print("📋 TRAINING CONFIGURATION")
print("=" * 60)
print(f"  Epochs:         {EPOCHS}")
print(f"  Batch size:     {BATCH_SIZE}")
print(f"  Save frequency: Every {SAVE_FREQ} epoch(s)")
print(f"  Checkpoint:     /content/drive/MyDrive/PromptPAR_checkpoints/Vit_Market1501")
print("=" * 60)

# Commented out IPython magic to ensure Python compatibility.
# ╔══════════════════════════════════════════════════════════════╗
# ║  CELL 10: TRAINING (LƯU THẲNG VÀO DRIVE)                     ║
# ╚══════════════════════════════════════════════════════════════╝

# %cd /content/OpenPAR/PromptPAR

import os

# Tạo thư mục trong Drive
CHECKPOINT_DIR = "/content/drive/MyDrive/PromptPAR_checkpoints/Vit_Market1501"
os.makedirs(CHECKPOINT_DIR, exist_ok=True)

# Tạo symlink từ local output sang Drive
LOCAL_OUTPUT = "/content/OpenPAR/PromptPAR/exp_result"
if os.path.exists(LOCAL_OUTPUT):
    if os.path.islink(LOCAL_OUTPUT):
        os.unlink(LOCAL_OUTPUT) # Remove symbolic link directly
    elif os.path.isdir(LOCAL_OUTPUT):
        import shutil
        shutil.rmtree(LOCAL_OUTPUT) # Remove directory
os.symlink(CHECKPOINT_DIR, LOCAL_OUTPUT)

print(f" Symlink: {LOCAL_OUTPUT} → {CHECKPOINT_DIR}")
print(" Bắt đầu training.. .\n")

!  python train.py Market1501 \
    --batchsize 16 \
    --epoch 30 \
    --height 224 \
    --width 224 \
    --lr 8e-3 \
    --weight_decay 1e-4 \
    --clip_lr 4e-3 \
    --clip_weight_decay 1e-4 \
    --text_prompt 3 \
    --vis_prompt 50 \
    --vis_depth 24 \
    --div_num 4 \
    --overlap_row 2 \
    --mm_layers 1 \
    --smooth_param 0.1 \
    --ag_threshold 0.5 \
    --train_split trainval \
    --valid_split test \
    --save_freq 5 \
    --use_div \
    --use_textprompt \
    --use_mm_former \
    --use_GL \
    --dir $CHECKPOINT_DIR

# ╔══════════════════════════════════════════════════════════════╗
# ║  CELL 11: KIỂM TRA CHECKPOINT                                ║
# ╚══════════════════════════════════════════════════════════════╝

import os
import glob

CHECKPOINT_DIR = "/content/drive/MyDrive/PromptPAR_checkpoints/Vit_Market1501"

print("📁 Checkpoints đã lưu:")
print("=" * 60)

# Tìm trong Drive
checkpoints = glob.glob(f'{CHECKPOINT_DIR}/**/*.pth', recursive=True)
checkpoints += glob.glob(f'{CHECKPOINT_DIR}/*. pth')

# Tìm trong local
local_ckpts = glob.glob('/content/OpenPAR/PromptPAR/**/*.pth', recursive=True)

if checkpoints:
    print(f"✅ Google Drive ({len(checkpoints)} files):")
    for ckpt in checkpoints:
        size = os.path. getsize(ckpt) / 1024 / 1024
        print(f"   📦 {os.path.basename(ckpt)} ({size:.1f} MB)")

if local_ckpts:
    print(f"\n📁 Local ({len(local_ckpts)} files):")
    for ckpt in local_ckpts:
        size = os. path.getsize(ckpt) / 1024 / 1024
        print(f"   📦 {os.path.basename(ckpt)} ({size:.1f} MB)")

    # Copy to Drive
    import shutil
    print("\n🔄 Copying to Drive...")
    for ckpt in local_ckpts:
        dest = os.path.join(CHECKPOINT_DIR, os.path.basename(ckpt))
        shutil. copy(ckpt, dest)
        print(f"   ✅ {os.path.basename(ckpt)}")

if not checkpoints and not local_ckpts:
    print("❌ Chưa có checkpoint nào!")

# Commented out IPython magic to ensure Python compatibility.
# ╔══════════════════════════════════════════════════════════════╗
# ║  CELL 12: RESUME TRAINING (NẾU BỊ NGẮT)                      ║
# ╚══════════════════════════════════════════════════════════════╝

# ⚠️ UNCOMMENT VÀ CHẠY NẾU COLAB BỊ NGẮT
# Trước tiên chạy Cell 1, 7, rồi chạy cell này


# %cd /content/OpenPAR/PromptPAR

import os
CHECKPOINT_DIR = "/content/drive/MyDrive/PromptPAR_checkpoints/Vit_Market1501"

! python train.py Market1501 \
    --batchsize 16 \
    --epoch 30 \
    --height 224 \
    --width 224 \
    --lr 8e-3 \
    --weight_decay 1e-4 \
    --clip_lr 4e-3 \
    --text_prompt 3 \
    --vis_prompt 50 \
    --vis_depth 24 \
    --div_num 4 \
    --save_freq 5 \
    --use_div \
    --use_textprompt \
    --use_mm_former \
    --checkpoint \
    --dir $CHECKPOINT_DIR

print("💡 Uncomment code trên và chạy nếu cần resume training")